version: "3"
services:

  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  
  node-app:
    build: .
    image: node-app #thr33fold/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cloud_user
      - MONGO_INITDB_ROOT_PASSWORD=cloud_pass
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: