version: "3"
services:

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
      - user
      - frontend
  
  user:
    build:
      context: .
      dockerfile: user.Dockerfile
    image: user
    environment:
      - PORT=3001
    depends_on:
      - mongo
      - redis
  
  node-app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: node-app
    environment:
      - PORT=3002
    depends_on:
      - user

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend
    environment:
      - PORT=3000
    depends_on:
      - user
      - node-app

  
  mongo:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cloud_user
      - MONGO_INITDB_ROOT_PASSWORD=cloud_pass
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: